### ISSUE TITLE
Add a "point up" hex grid

### ISSUE THREAD

**Issue by mcnees** [mcnees/LaTeX-Graph-Paper#18]
Just add this as a setting to get around the "set the page to landscape" hack

**Comment by duetosymmetry** [comment]
I think the approach that would duplicate the least code would be to add a rotation argument to the hex pgf pattern; then the normal hex pattern would use no rotation, and the hex-up pattern would pass an argument of 90 degrees.

**Comment by duetosymmetry** [comment]
[Relatedly, iso and tri are duplicates with a rotation; and, there is duplication between std and stdeight, which are the same code but with different default values for \GP@patternsize and default margins]

**Comment by mcnees** [comment]
I rewrote the hexagon pattern to add rotations, and added a hexup option. See the rotated-hexagons branch. If this is fine I can do the triangles, as well. The only issue is I explicitly set the lower left corner of the bounding box to (0,0) instead of \pgfpointorigin -- not sure how to use that function here.

**Comment by mcnees** [comment]
Went ahead and did triangles do. There's a pull request.

**Comment by duetosymmetry** [comment]
Closed via #19
