### ISSUE TITLE
Title for Page?

### ISSUE THREAD

**Issue by aeu** [mcnees/LaTeX-Graph-Paper#27]
Hello,

Thank you for putting this out there.  I am currently using it for my son for his math homework in order to help him line his numbers up.  I did have a question - how would I add a title (for example his name) to the page?  I tried a couple of snippets here and there such as eso-pic, but I end up with the grid pushed off the page.

Thanks!

**Comment by duetosymmetry** [comment]
The grid pattern is suppose to be in the background of the page, so anything you put in the document should end up on top of it. Here's an example:
```tex
\documentclass{article}
\usepackage[pattern=majmin, colorset=precocious]{gridpapers}

\begin{document}
\title{My document title}
\date{} % I don't want a date
\maketitle
\end{document}
```
and it will look like this:
<img width="722" alt="image" src="https://github.com/user-attachments/assets/45046faf-a5e1-4138-9e57-0e4326f57f5f">

**Comment by aeu** [comment]
@duetosymmetry   sweet, thank you!
