### ISSUE TITLE
How to change paper size?

### ISSUE THREAD

**Issue by iamjoewoods** [mcnees/LaTeX-Graph-Paper#4]
I read the comment that the values are hard coded for Letter size. I wanted to change them to standardized A4 size. How can I o about doing so? 
I don't know Latex but will be willing to learn it to change the values.

**Comment by mcnees** [comment]
There's now an initial commit of a package with a paper size option. Some patterns don't yet work with all paper sizes, but we'll eventually fix those. If you try the new package out you can file issues for specific patterns that don't work away from letter size.
