### ISSUE TITLE
Latex package

### ISSUE THREAD

**Issue by jspc** [mcnees/LaTeX-Graph-Paper#5]
It'd be cool if this functionality could be imported as a package, rather than having to edit the file, compile, edit again.

Has there been any thought about this? Is it a no-go for any reason? Or would a PR be welcome?

**Comment by mcnees** [comment]
It's not a no-go at all, I just don't have time to regularly work on it. I'm totally open to folks using the code however they like, including making a LaTeX package out of it.

**Comment by mcnees** [comment]
There's now an initial commit of a package (thanks @duetosymmetry!).
